id: P000763
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25464
  title: རི་མོར་བལྟས་ནས་རྒྱལ་དར་ངོས་འཛིན་པ།
  author: ''
  volumes:
    75ccabb03d504046940890c09e716780:
      image_group_id: I1KG25466
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
